name: linked issue

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  required:
    runs-on: ubuntu-latest
    permissions:
        issues: read
        pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "dependabot/**"
          loose-matching: true